import { Hono } from "hono";
import type { Bindings } from "../bindings";

export const imagesRoute = new Hono<{ Bindings: Bindings }>();

// Key format: {publicId}/{uuid}-{filename} — keep in sync with buildImageKey (~/server/images).
// Case-sensitive by design: all UUIDs are generated by crypto.randomUUID() which always
// produces lowercase hex, so uppercase keys are never issued by this application.
const KEY_PATTERN = /^[a-f0-9-]{36}\/[a-f0-9-]{36}-[\w.-]+$/;

// Serve image from R2
imagesRoute.get("/:key{.+}", async (c) => {
  const key = c.req.param("key");

  if (!key || !KEY_PATTERN.test(key)) {
    return c.json({ error: "Invalid key format" }, 400);
  }

  // Keys are immutable (UUID-based), so honor conditional requests: when the
  // client's If-None-Match matches, R2 returns no body and we reply 304.
  const object = await c.env.BUCKET.get(key, {
    onlyIf: c.req.raw.headers,
  });

  if (!object) {
    return c.json({ error: "Image not found" }, 404);
  }

  const headers = new Headers();
  headers.set("Content-Type", object.httpMetadata?.contentType || "image/jpeg");
  headers.set("Cache-Control", "public, max-age=31536000, immutable");
  // Prevent the browser from MIME-sniffing a stored file into an executable type.
  headers.set("X-Content-Type-Options", "nosniff");
  if (object.httpEtag) {
    headers.set("ETag", object.httpEtag);
  }

  // R2 omits the body when a conditional (onlyIf) precondition fails.
  if (!("body" in object)) {
    return new Response(null, { status: 304, headers });
  }

  return new Response(object.body, { headers });
});
